### ISSUE TITLE
`like`, `contains`, and other criteria modifiers don't work

### ISSUE THREAD

**Issue by ksmithut** [nutanix/sails-forcedotcom#13]
https://github.com/balderdashy/waterline-docs/blob/master/queries/query-language.md#criteria-modifiers

Criteria modifiers don't work. The modifier object just gets stringified into `'[object Object]'`.

```js
User.find({
  name: { like: '% Smith%' }
});

// makes a query like this: WHERE name = [object Object]
```

**Comment by toledosteve** [comment]
I'm also trying to get this to work, specifically the '>' to translate to '$gt'.  

@ksmithut - I was, however, able to get the like statement to work doing the following:

```javascript
User.find({
    name: { '$like': '%Smith%' }
}):
```
Unfortunately this trick isn't working for me for other modifiers.

**Comment by ksmithut** [comment]
(Shameful plug) @toledosteve it didn't look like much work was being done on this module, so we wrote our own. It's still in the early stages of implementation, but you could give it a try. It has most of the criteria modifiers implemented. [`waterline-salesforce`](https://www.npmjs.com/package/waterline-salesforce). Documentation is also somewhat lacking... Feel free to open a PR or issue with questions.
